"""Layouts das tabelas de gtmode_data.dat e gtmode_race.dat do GT2.

Gerado a partir das estruturas documentadas por pez2k em gt2tools
(https://github.com/pez2k/gt2tools, GT2DataSplitter/DataStructures), com
autorização do dono do projeto Apex Garage para uso como referência.
Cada campo: (nome, formato struct, quantidade). Tudo little-endian, sem
preenchimento entre campos (Pack = 1). `None` = estrutura sem campos
mapeados; só o tamanho é conhecido.
"""

# Ordem dos blocos dentro de gtmode_data.dat (índice no cabeçalho).
ORDEM_GTMODE_DATA = [
    "Brake",
    "BrakeController",
    "Steer",
    "Chassis",
    "Lightweight",
    "RacingModify",
    "Engine",
    "PortPolish",
    "EngineBalance",
    "Displacement",
    "Computer",
    "NATune",
    "TurbineKit",
    "Drivetrain",
    "Flywheel",
    "Clutch",
    "PropellerShaft",
    "Gear",
    "Suspension",
    "Intercooler",
    "Muffler",
    "LSD",
    "TiresFront",
    "TiresRear",
    "TireSize",
    "TireCompound",
    "TireForceVol",
    "ActiveStabilityControl",
    "TractionControlSystem",
    "Wheel",
    "Car",
]

# Ordem dos blocos dentro de gtmode_race.dat; depois deles vem a tabela ASCII.
ORDEM_GTMODE_RACE = ["Event", "EnemyCars", "Regulations"]

LAYOUTS = {
    "Brake": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("BrakingPower", "B", 1),
        ("FrontBrakesUnknown", "B", 1),
        ("RearBrakesUnknown", "B", 1),
    ]},
    "BrakeController": {"tamanho": 16, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("MaxFrontBias", "B", 1),
        ("Unknown", "B", 1),
        ("Unknown2", "B", 1),
        ("DefaultBias", "B", 1),
        ("MaxRearBias", "B", 1),
        ("Unknown3", "B", 1),
        ("Unknown4", "B", 1),
    ]},
    "Steer": {"tamanho": 24, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("Unknown1", "B", 1),
        ("Angle1Speed", "B", 1),
        ("Angle2Speed", "B", 1),
        ("Angle3Speed", "B", 1),
        ("Angle4Speed", "B", 1),
        ("Angle5Speed", "B", 1),
        ("Angle6Speed", "B", 1),
        ("Angle1", "B", 1),
        ("Angle2", "B", 1),
        ("Angle3", "B", 1),
        ("Angle4", "B", 1),
        ("Angle5", "B", 1),
        ("Angle6", "B", 1),
        ("MaxSteeringAngle", "B", 1),
        ("Unknown2", "B", 1),
    ]},
    "Chassis": {"tamanho": 20, "campos": [
        ("CarId", "I", 1),
        ("FrontWeightDistribution", "B", 1),
        ("Unknown2", "B", 1),
        ("FrontGrip", "B", 1),
        ("RearGrip", "B", 1),
        ("Length", "H", 1),
        ("Height", "H", 1),
        ("Wheelbase", "H", 1),
        ("Weight", "H", 1),
        ("TurningResistance", "B", 1),
        ("PitchResistance", "B", 1),
        ("RollResistance", "B", 1),
        ("Unknown8", "B", 1),
    ]},
    "Lightweight": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Weight", "H", 1),
        ("Unknown", "B", 1),
        ("Stage", "B", 1),
    ]},
    "RacingModify": {"tamanho": 28, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("BodyId", "I", 1),
        ("Weight", "B", 1),
        ("BodyRollAmount", "B", 1),
        ("Stage", "B", 1),
        ("Drag", "B", 1),
        ("FrontDownforceMinimum", "B", 1),
        ("FrontDownforceMaximum", "B", 1),
        ("FrontDownforceDefault", "B", 1),
        ("RearDownforceMinimum", "B", 1),
        ("RearDownforceMaximum", "B", 1),
        ("RearDownforceDefault", "B", 1),
        ("Unknown3", "B", 1),
        ("Unknown4", "B", 1),
        ("Unknown5", "B", 1),
        ("Unknown6", "B", 1),
        ("Width", "H", 1),
    ]},
    "Engine": {"tamanho": 76, "campos": [
        ("CarId", "I", 1),
        ("LayoutName", "H", 1),
        ("ValvetrainName", "H", 1),
        ("Aspiration", "H", 1),
        ("SoundFile", "H", 1),
        ("TorqueCurve1", "h", 1),
        ("TorqueCurve2", "h", 1),
        ("TorqueCurve3", "h", 1),
        ("TorqueCurve4", "h", 1),
        ("TorqueCurve5", "h", 1),
        ("TorqueCurve6", "h", 1),
        ("TorqueCurve7", "h", 1),
        ("TorqueCurve8", "h", 1),
        ("TorqueCurve9", "h", 1),
        ("TorqueCurve10", "h", 1),
        ("TorqueCurve11", "h", 1),
        ("TorqueCurve12", "h", 1),
        ("TorqueCurve13", "h", 1),
        ("TorqueCurve14", "h", 1),
        ("TorqueCurve15", "h", 1),
        ("TorqueCurve16", "h", 1),
        ("Displacement", "H", 1),
        ("DisplayedPower", "H", 1),
        ("MaxPowerRPM", "H", 1),
        ("DisplayedTorque", "H", 1),
        ("MaxTorqueRPMName", "H", 1),
        ("PowerMultiplier", "B", 1),
        ("ClutchReleaseRPM", "B", 1),
        ("IdleRPM", "B", 1),
        ("MaxRPM", "B", 1),
        ("RedlineRPM", "B", 1),
        ("TorqueCurveRPM1", "B", 1),
        ("TorqueCurveRPM2", "B", 1),
        ("TorqueCurveRPM3", "B", 1),
        ("TorqueCurveRPM4", "B", 1),
        ("TorqueCurveRPM5", "B", 1),
        ("TorqueCurveRPM6", "B", 1),
        ("TorqueCurveRPM7", "B", 1),
        ("TorqueCurveRPM8", "B", 1),
        ("TorqueCurveRPM9", "B", 1),
        ("TorqueCurveRPM10", "B", 1),
        ("TorqueCurveRPM11", "B", 1),
        ("TorqueCurveRPM12", "B", 1),
        ("TorqueCurveRPM13", "B", 1),
        ("TorqueCurveRPM14", "B", 1),
        ("TorqueCurveRPM15", "B", 1),
        ("TorqueCurveRPM16", "B", 1),
        ("TorqueCurvePoints", "B", 1),
    ]},
    "PortPolish": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "EngineBalance": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "Displacement": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "Computer": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "NATune": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandRPMIncrease", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "TurbineKit": {"tamanho": 20, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("BoostGaugeLimit", "B", 1),
        ("LowRPMBoost", "B", 1),
        ("HighRPMBoost", "B", 1),
        ("SpoolRate", "B", 1),
        ("Unknown1", "B", 1),
        ("Unknown2", "B", 1),
        ("Unknown3", "B", 1),
        ("RPMIncrease", "b", 1),
        ("RedlineIncrease", "b", 1),
        ("HighRPMPowerMultiplier", "B", 1),
        ("LowRPMPowerMultiplier", "B", 1),
    ]},
    "Drivetrain": {"tamanho": 16, "campos": [
        ("CarId", "I", 1),
        ("Unknown", "B", 1),
        ("Unknown2", "B", 1),
        ("Unknown3", "B", 1),
        ("Unknown4", "B", 1),
        ("DrivetrainType", "B", 1),
        ("AWDBehaviour", "B", 1),
        ("DefaultClutchRPMDropRate", "B", 1),
        ("DefaultClutchInertiaEngaged", "B", 1),
        ("DefaultClutchInertialWeight", "B", 1),
        ("DefaultClutchInertiaDisengaged", "B", 1),
        ("FrontDriveInertia", "B", 1),
        ("RearDriveInertia", "B", 1),
    ]},
    "Flywheel": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("RPMDropRate", "B", 1),
        ("ShiftDelay", "B", 1),
        ("InertialWeight", "B", 1),
    ]},
    "Clutch": {"tamanho": 16, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("RPMDropRate", "B", 1),
        ("InertiaDisengaged", "B", 1),
        ("InertiaEngaged", "B", 1),
        ("InertialWeight", "B", 1),
        ("InertiaBraking", "B", 1),
        ("Unknown1", "B", 1),
        ("Unknown2", "B", 1),
    ]},
    "PropellerShaft": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("RPMDropRate", "B", 1),
        ("Inertia", "B", 1),
        ("Inertia2", "B", 1),
    ]},
    "Gear": {"tamanho": 36, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("NumberOfGears", "B", 1),
        ("ReverseGearRatio", "h", 1),
        ("FirstGearRatio", "h", 1),
        ("SecondGearRatio", "h", 1),
        ("ThirdGearRatio", "h", 1),
        ("FourthGearRatio", "h", 1),
        ("FifthGearRatio", "h", 1),
        ("SixthGearRatio", "h", 1),
        ("SeventhGearRatio", "h", 1),
        ("DefaultFinalDriveRatio", "h", 1),
        ("MaxFinalDriveRatio", "h", 1),
        ("MinFinalDriveRatio", "h", 1),
        ("AllowIndividualRatioAdjustments", "B", 1),
        ("DefaultAutoSetting", "B", 1),
        ("MinAutoSetting", "B", 1),
        ("MaxAutoSetting", "B", 1),
    ]},
    "Suspension": {"tamanho": 76, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("MinCamberFront", "B", 1),
        ("MaxCamberFront", "B", 1),
        ("DefaultCamberFront", "B", 1),
        ("MinCamberRear", "B", 1),
        ("MaxCamberRear", "B", 1),
        ("DefaultCamberRear", "B", 1),
        ("MinToeFront", "B", 1),
        ("MaxToeFront", "B", 1),
        ("MinToeRear", "B", 1),
        ("MaxToeRear", "B", 1),
        ("MinHeightFront", "B", 1),
        ("MaxHeightFront", "B", 1),
        ("DefaultHeightFront", "B", 1),
        ("MinHeightRear", "B", 1),
        ("MaxHeightRear", "B", 1),
        ("DefaultHeightRear", "B", 1),
        ("DampingFront", "B", 1),
        ("DampingRear", "B", 1),
        ("TravelFront", "B", 1),
        ("TravelRear", "B", 1),
        ("MinSpringRateFront", "B", 1),
        ("MaxSpringRateFront", "B", 1),
        ("DefaultSpringRateFront", "B", 1),
        ("MinSpringRateRear", "B", 1),
        ("MaxSpringRateRear", "B", 1),
        ("DefaultSpringRateRear", "B", 1),
        ("SpringFrequencyFront", "B", 1),
        ("SpringFrequencyRear", "B", 1),
        ("Unknown7", "B", 1),
        ("Unknown8", "B", 1),
        ("MaxDamperBoundFront", "B", 1),
        ("Unknown9", "B", 1),
        ("Unknown10", "B", 1),
        ("DefaultDamperBoundFront", "B", 1),
        ("Unknown11", "B", 1),
        ("Unknown12", "B", 1),
        ("Unknown13", "B", 1),
        ("MaxDamperReboundFront", "B", 1),
        ("Unknown14", "B", 1),
        ("Unknown15", "B", 1),
        ("DefaultDamperReboundFront", "B", 1),
        ("Unknown16", "B", 1),
        ("Unknown17", "B", 1),
        ("Unknown18", "B", 1),
        ("MaxDamperBoundRear", "B", 1),
        ("Unknown19", "B", 1),
        ("Unknown20", "B", 1),
        ("DefaultDamperBoundRear", "B", 1),
        ("Unknown21", "B", 1),
        ("Unknown22", "B", 1),
        ("Unknown23", "B", 1),
        ("MaxDamperReboundRear", "B", 1),
        ("Unknown24", "B", 1),
        ("Unknown25", "B", 1),
        ("DefaultDamperReboundRear", "B", 1),
        ("Unknown26", "B", 1),
        ("Unknown27", "B", 1),
        ("Unknown28", "B", 1),
        ("MaxStabiliserFront", "B", 1),
        ("Unknown29", "B", 1),
        ("Unknown30", "B", 1),
        ("DefaultStabiliserFront", "B", 1),
        ("MaxStabiliserRear", "B", 1),
        ("Unknown31", "B", 1),
        ("Unknown32", "B", 1),
        ("DefaultStabiliserRear", "B", 1),
        ("Unknown33", "B", 1),
    ]},
    "Intercooler": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "Muffler": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("PowerbandScaling", "b", 1),
        ("RPMIncrease", "b", 1),
        ("PowerMultiplier", "B", 1),
    ]},
    "LSD": {"tamanho": 32, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("Unknown", "B", 1),
        ("Unknown2", "B", 1),
        ("Unknown3", "B", 1),
        ("FrontUnknown", "B", 1),
        ("DefaultInitialFront", "B", 1),
        ("MinInitialFront", "B", 1),
        ("MaxInitialFront", "B", 1),
        ("DefaultAccelFront", "B", 1),
        ("MinAccelFront", "B", 1),
        ("MaxAccelFront", "B", 1),
        ("DefaultDecelFront", "B", 1),
        ("MinDecelFront", "B", 1),
        ("MaxDecelFront", "B", 1),
        ("RearUnknown", "B", 1),
        ("DefaultInitialRear", "B", 1),
        ("MinInitialRear", "B", 1),
        ("MaxInitialRear", "B", 1),
        ("DefaultAccelRear", "B", 1),
        ("MinAccelRear", "B", 1),
        ("MaxAccelRear", "B", 1),
        ("DefaultDecelRear", "B", 1),
        ("MinDecelRear", "B", 1),
        ("MaxDecelRear", "B", 1),
    ]},
    "TiresFront": {"tamanho": 16, "campos": [
        ("CarId", "I", 1),
        ("Price", "I", 1),
        ("Stage", "B", 1),
        ("SteeringReaction1", "B", 1),
        ("WheelSize", "B", 1),
        ("SteeringReaction2", "B", 1),
        ("TireCompound", "B", 1),
        ("TireForceVolMaybe", "B", 1),
        ("SlipMultiplier", "B", 1),
        ("GripMultiplier", "B", 1),
    ]},
    "TiresRear": {"tamanho": 12, "campos": [
        ("CarId", "I", 1),
        ("Stage", "B", 1),
        ("SteeringReaction1", "B", 1),
        ("WheelSize", "B", 1),
        ("SteeringReaction2", "B", 1),
        ("TireCompound", "B", 1),
        ("TireForceVolMaybe", "B", 1),
        ("SlipMultiplier", "B", 1),
        ("GripMultiplier", "B", 1),
    ]},
    "TireSize": {"tamanho": 4, "campos": [
        ("DiameterInches", "B", 1),
        ("WidthMM", "B", 1),
        ("Profile", "B", 1),
        ("Padding", "B", 1),
    ]},
    "TireCompound": {"tamanho": 64, "campos": None},
    "TireForceVol": {"tamanho": 8, "campos": [
        ("TarmacGrip", "B", 1),
        ("GuideGrip", "B", 1),
        ("GreenGrip", "B", 1),
        ("SandGrip", "B", 1),
        ("GravelGrip", "B", 1),
        ("DirtGrip", "B", 1),
        ("WaterGripMaybe", "B", 1),
        ("Padding", "B", 1),
    ]},
    "ActiveStabilityControl": {"tamanho": 16, "campos": None},
    "TractionControlSystem": {"tamanho": 16, "campos": None},
    "Wheel": {"tamanho": 8, "campos": [
        ("WheelId", "I", 1),
        ("StageMaybe", "B", 1),
        ("Unknown", "B", 1),
        ("Unknown2", "B", 1),
        ("Unknown3", "B", 1),
    ]},
    "Car": {"tamanho": 72, "campos": [
        ("CarId", "I", 1),
        ("Brake", "H", 1),
        ("BrakeController", "H", 1),
        ("Steer", "H", 1),
        ("Chassis", "H", 1),
        ("Lightweight", "H", 1),
        ("RacingModify", "H", 1),
        ("Engine", "H", 1),
        ("PortPolish", "H", 1),
        ("EngineBalance", "H", 1),
        ("Displacement", "H", 1),
        ("Computer", "H", 1),
        ("NATune", "H", 1),
        ("TurbineKit", "H", 1),
        ("Drivetrain", "H", 1),
        ("Flywheel", "H", 1),
        ("Clutch", "H", 1),
        ("PropellerShaft", "H", 1),
        ("LSD", "H", 1),
        ("Gear", "H", 1),
        ("Suspension", "H", 1),
        ("Intercooler", "H", 1),
        ("Muffler", "H", 1),
        ("TiresFront", "H", 1),
        ("TiresRear", "H", 1),
        ("ActiveStabilityControl", "H", 1),
        ("TractionControlSystem", "H", 1),
        ("RimsCode3", "H", 1),
        ("ManufacturerID", "H", 1),
        ("NameFirstPart", "H", 1),
        ("NameSecondPart", "H", 1),
        ("HasAllTiresBought", "B", 1),
        ("Year", "B", 1),
        ("Unknown", "H", 1),
        ("Price", "I", 1),
    ]},
    "Event": {"tamanho": 156, "campos": [
        ("EventName", "H", 1),
        ("TrackName", "H", 1),
        ("Opponent1", "I", 1),
        ("Opponent2", "I", 1),
        ("Opponent3", "I", 1),
        ("Opponent4", "I", 1),
        ("Opponent5", "I", 1),
        ("Opponent6", "I", 1),
        ("Opponent7", "I", 1),
        ("Opponent8", "I", 1),
        ("Opponent9", "I", 1),
        ("Opponent10", "I", 1),
        ("Opponent11", "I", 1),
        ("Opponent12", "I", 1),
        ("Opponent13", "I", 1),
        ("Opponent14", "I", 1),
        ("Opponent15", "I", 1),
        ("Opponent16", "I", 1),
        ("RollingStartSpeed", "B", 1),
        ("Laps", "B", 1),
        ("AutoDrive", "B", 1),
        ("Licence", "B", 1),
        ("AIFrontGripRWD", "B", 1),
        ("AIFrontGripFWD", "B", 1),
        ("AIFrontGrip4WD", "B", 1),
        ("AIFrontGripSpecial4WD", "B", 1),
        ("AIRearGripRWD", "B", 1),
        ("AIRearGripFWD", "B", 1),
        ("AIRearGrip4WD", "B", 1),
        ("AIRearGripSpecial4WD", "B", 1),
        ("AIAccelerationRWD", "B", 1),
        ("AIAccelerationFWD", "B", 1),
        ("AIAcceleration4WD", "B", 1),
        ("AIAccelerationSpecial4WD", "B", 1),
        ("AIThrottleLiftReductionRWD", "B", 1),
        ("AIThrottleLiftReductionFWD", "B", 1),
        ("AIThrottleLiftReduction4WD", "B", 1),
        ("AIThrottleLiftReductionSpecial4WD", "B", 1),
        ("AIRubberBandMultiplier", "B", 1),
        ("AIRubberBandUnknown1", "B", 1),
        ("AIRubberBandScaledPerCar", "B", 1),
        ("AIRubberBandLeadingSlowdownPercentage", "B", 1),
        ("AIRubberBandLeadingScalingDistance", "H", 1),
        ("AIRubberBandTrailingSpeedupPercentage", "B", 1),
        ("AIRubberBandTrailingScalingDistance", "H", 1),
        ("TireWearOrangeDurationMultiplier", "B", 1),
        ("TireWearOrangeGripLoss", "B", 1),
        ("TireWearUnknown", "B", 1),
        ("TireWearBlueDurationMultiplier", "B", 1),
        ("TireWearBlueGripLoss", "B", 1),
        ("TireWearGreenDurationMultiplier", "B", 1),
        ("TireWearGreenGripLoss", "B", 1),
        ("Unknown1", "I", 1),
        ("Unknown2", "I", 1),
        ("Unknown3", "I", 1),
        ("Unknown4", "B", 1),
        ("IsRally", "B", 1),
        ("EligibleCarsRestriction", "B", 1),
        ("DrivetrainRestriction", "B", 1),
        ("PrizeMoney1st", "H", 1),
        ("PrizeMoney2nd", "H", 1),
        ("PrizeMoney3rd", "H", 1),
        ("PrizeMoney4th", "H", 1),
        ("PrizeMoney5th", "H", 1),
        ("PrizeMoney6th", "H", 1),
        ("PrizeCars", "I", 4),
        ("TrackBannerPool", "H", 1),
        ("PSRestriction", "H", 1),
        ("SeriesChampBonus", "H", 1),
        ("CarRestrictionFlags", "H", 1),
    ]},
    "EnemyCars": {"tamanho": 96, "campos": [
        ("CarId", "I", 1),
        ("Brake", "H", 1),
        ("BrakeController", "H", 1),
        ("Steer", "H", 1),
        ("Chassis", "H", 1),
        ("Lightweight", "H", 1),
        ("RacingModify", "H", 1),
        ("Engine", "H", 1),
        ("PortPolish", "H", 1),
        ("EngineBalance", "H", 1),
        ("Displacement", "H", 1),
        ("Computer", "H", 1),
        ("NATune", "H", 1),
        ("TurbineKit", "H", 1),
        ("Drivetrain", "H", 1),
        ("Flywheel", "H", 1),
        ("Clutch", "H", 1),
        ("Propshaft", "H", 1),
        ("LSD", "H", 1),
        ("Gear", "H", 1),
        ("Suspension", "H", 1),
        ("Intercooler", "H", 1),
        ("Muffler", "H", 1),
        ("TiresFront", "H", 1),
        ("TiresRear", "H", 1),
        ("ActiveStabilityControl", "H", 1),
        ("TractionControlSystem", "H", 1),
        ("RimsCode3", "H", 1),
        ("FinalDriveRatio", "H", 1),
        ("GearAutoSetting", "B", 1),
        ("LSDInitialFront", "B", 1),
        ("LSDAccelFront", "B", 1),
        ("LSDDecelFront", "B", 1),
        ("LSDInitialRearAYCLevel", "B", 1),
        ("LSDAccelRear", "B", 1),
        ("LSDDecelRear", "B", 1),
        ("DownforceFront", "B", 1),
        ("DownforceRear", "B", 1),
        ("CamberFront", "B", 1),
        ("CamberRear", "B", 1),
        ("ToeFront", "B", 1),
        ("ToeRear", "B", 1),
        ("RideHeightFront", "B", 1),
        ("RideHeightRear", "B", 1),
        ("SpringRateFront", "B", 1),
        ("SpringRateRear", "B", 1),
        ("DamperBoundFront1", "B", 1),
        ("DamperBoundFront2", "B", 1),
        ("DamperReboundFront1", "B", 1),
        ("DamperReboundFront2", "B", 1),
        ("DamperBoundRear1", "B", 1),
        ("DamperBoundRear2", "B", 1),
        ("DamperReboundRear1", "B", 1),
        ("DamperReboundRear2", "B", 1),
        ("StabiliserFront", "B", 1),
        ("StabiliserRear", "B", 1),
        ("ASMLevel", "B", 1),
        ("TCSLevel", "B", 1),
        ("Unknown3", "B", 1),
        ("Unknown4", "H", 1),
        ("PowerMultiplier", "H", 1),
        ("OpponentId", "H", 1),
    ]},
    "Regulations": {"tamanho": 128, "campos": [
        ("EligibleCarIds", "I", 32),
    ]},
}
