name: Testes

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot 4.4
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.4.1
          use-dotnet: false

      - name: Rodar testes
        run: tests/rodar.sh
